apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-manuel-diaz
  labels:
    app: jenkins-agent-manuel-diaz
spec:
  containers:
  - name: node-docker-kubectl
    # Cambiamos a esta imagen porque ya trae Node.js y herramientas de sistema
    image: node:22-bookworm
    # Forzamos ejecución como root para evitar errores de 'Permission denied'
    securityContext:
      runAsUser: 0
    # Asignamos recursos estables
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    command: ['cat']
    tty: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  volumes:
  - name: workspace-volume
    emptyDir: {}
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
