apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-manuel-diaz
  labels:
    app: jenkins-agent-manuel-diaz
spec:
  containers:
  - name: node-docker-kubectl
    image: node:22-bookworm
    securityContext:
      runAsUser: 0
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  # Contenedor Sidecar: El motor de Docker independiente
  - name: dind
    image: docker:27.0-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  volumes:
  - name: workspace-volume
    emptyDir: {}
